#!/usr/bin/env zsh

() {

# Determine OS type.
local system_type=$(uname)
if [[ $system_type == Darwin ]]; then
  export IS_MACOS=1
elif [[ $system_type == Linux ]]; then
  export IS_LINUX=1
elif [[ $system_type == FreeBSD ]]; then
  export IS_FREEBSD=1
else
  echo "⚠️ Unknown OS!"
fi

}