unbind -a

### Server options
set -s set-clipboard on
set -sa terminal-overrides ',*:Ms=\E]52;%p1%s;%p2%s\007'

### Global options
# Shell
# Stale SSH_AUTH_SOCK fix. Removes SSH_AUTH_SOCK to disable tmux automatically re-setting the variable on connect.
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
set -g default-shell /bin/zsh   # Change shell to zsh

# Display
set -g display-time 4000        # Increase tmux messages display duration from 750ms to 4s
set -g message-limit 0          # Disable saving errors in client message log
set -g history-limit 10000      # Infinite scrollback buffer
set -g status off               # Disable status bar

# Key / escape sequence behaviour
set -g escape-time 1            # Time in milliseconds to determine if an escape input is part of a function or meta key sequences
set -g prefix None              # Clear prefix key
set -g prefix2 None             # Clear secondary prefix key
set -g assume-paste-time 0      # Always process tmux key bindings
set -g focus-events off         # Focus events enabled for terminals that support them
set -g allow-passthrough on     # Allow programs in the pane to bypass tmux using a terminal escape sequence

# Titles
set -g set-titles on            # Automatically set client terminal title
set -g set-titles-string "#T"   # Set client terminal title to pane title (can be set by application)
set -g automatic-rename off     # Disable automatic window re-naming
