#!/usr/bin/env zsh
#MISE dir="{{cwd}}"
#MISE depends=["init:config"]
#USAGE arg "[python-version]"
#USAGE flag "-I --no-init" help="Do not initialize project."

mise run init:py $usage_python_version

mise set UV_INIT_BUILD_BACKEND=uv
mise set UV_NATIVE_TLS=1
mise set UV_NO_MANAGED_PYTHON=1
mise set UV_UNMANAGED_INSTALL=1
[[ -f pyproject.toml || -n $usage_no_init ]] || mise exec -- uv init --lib --no-readme --description "" --vcs none
