#!/usr/bin/env zsh

local existing file homedir listed

file=$Z4H_PACKAGE_DIR/zcomet.zsh
[[ -e $file ]] || return 1

source $file
zcomet update

autoload -Uz -- $XDG_CONFIG_HOME/zsh/fn/init-zcomet
(( $+functions[init-zcomet] )) && init-zcomet
