#!/usr/bin/env zsh

local -aU repos snippets
zstyle -a ':my:zcomet:' repos     repos
zstyle -a ':my:zcomet:' snippets  snippets

z4h source agkozak/zcomet/zcomet.zsh
if (( ${#repos} )) { zcomet load $repos }
if (( ${#snippets} )) { zcomet snippet $snippets }
