#!/usr/bin/env zsh

emulate -L zsh

# This function is invoked by zsh4humans on every ssh command after
# the instructions from ssh-related zstyles have been applied. It allows
# us to configure ssh teleportation in ways that cannot be done with
# zstyles.
#
# Within this function we have readonly access to the following parameters:
#
# - z4h_ssh_client  local hostname
# - z4h_ssh_host    remote hostname as it was specified on the command line
#
# We also have read & write access to these:
#
# - z4h_ssh_enable          1 to use ssh teleportation, 0 for plain ssh
# - z4h_ssh_send_files      list of files to send to the remote; keys are local
#                           file names, values are remote file names
# - z4h_ssh_retrieve_files  the same as z4h_ssh_send_files but for pulling
#                           files from remote to local
# - z4h_retrieve_history    list of local files into which remote $HISTFILE
#                           should be merged at the end of the connection
# - z4h_ssh_command         command to use instead of `ssh`
#
# Additional, undocumented parameters:
#
# - user_host               the supplied user / host combination
# - z4h_ssh_prelude         shell commands to run before file transfer
# - z4h_ssh_setup           shell commands to run after file transfer but before
#                           starting z4h
# - z4h_ssh_teardown        shell commands to run when tearing down a z4h
#                           session

z4h_ssh_prelude+=(
  # Ensure zsh files are placed in $XDG_CONFIG_HOME, not the home root.
  'export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"; mkdir -p "$ZDOTDIR"'
)
z4h_ssh_setup+=(
  # Source env init script.
  '. ${XDG_CONFIG_HOME:-$HOME/.config}/env/-init'
)

# Extend possible SSH teleportation to config based on user@host:port zstyles.
local user host forwarding_agent
if [[ -n $user_host ]] {
  local ssh_config=$("$z4h_ssh_command[@]" $user_host -G)
  user=$(awk 'tolower($1) == "user" {print $2}' <<< $ssh_config)
  # Get the finalized hostname, falling back to original host.
  host=${$(awk 'tolower($1) == "hostname" {print $2}' <<< $ssh_config):-$z4h_host}
  forwarding_agent=$(awk 'tolower($1) == "forwardagent" {print $2}' <<< $ssh_config)
}
local -r user host forwarding_agent
local -r namespace=":my:z4h:ssh:$user:$host"

# Send indicated ENV vars. Use a configurable prefix when sending to work around
# potential sshd security configurations.
local vars_prefix
zstyle -s $namespace send-vars-prefix vars_prefix || vars_prefix='LC_MY_Z4H_'
local -a env_vars
zstyle -a $namespace send-vars env_vars
for var ($env_vars) {
  local prefixed_var="$vars_prefix$var"
  z4h_ssh_prelude+=("export $var=\"\$$prefixed_var\"; unset '$prefixed_var'")
  z4h_ssh_command+=("-o SetEnv='$prefixed_var=${(P)var}'")
}

# Enable or disable SSH teleportation based on custom config.
zstyle -t $namespace enable || z4h_ssh_enable=0
(( $z4h_ssh_enable )) || return 0

if [[ $forwarding_agent == yes ]] {
  z4h_ssh_setup+=(
    # Link the current SSH session's SSH_AUTH_SOCK to a well-known location, to
    # work around tmux not picking up the ENV var change automatically.
    "
    echo '$fg[yellow]z4h-ssh-configure$fg[default]: linking and re-exporting SSH_AUTH_SOCK'
    my_z4h_ssh_auth_sock=\"\$XDG_RUNTIME_DIR/ssh-agent.sock\"
    if test -e \"\$SSH_AUTH_SOCK\"; then
      ln -sf \"\$SSH_AUTH_SOCK\" \"\$my_z4h_ssh_auth_sock\" &&
        export SSH_AUTH_SOCK=\"\$my_z4h_ssh_auth_sock\"
    else
      rm -f \"\$my_z4h_ssh_auth_sock\"
    fi
    unset my_z4h_ssh_auth_sock
    "
  )
}

# Load extra files from custom namespace.
local -a extra_files
if zstyle -a $namespace send-extra-files extra_files; then
  local src dst
  for dst ($extra_files) {
    eval "src=$dst"
    z4h_ssh_send_files[$src]=${dst/#$HOME/\~}
  }
fi
if zstyle -a $namespace retrieve-extra-files extra_files; then
  local src dst
  for src ($extra_files) {
    eval "dst=$src"
    z4h_ssh_retrieve_files[$src]=${dst/#$HOME/\~}
  }
fi
