#!/usr/bin/env sh

# Explicitly set the XDG basedir spec, sinc some tools ignore the spec if
# not set.
[ -z "$XDG_RUNTIME_DIR" ] &&
  export XDG_RUNTIME_DIR=$(
    getconf DARWIN_USER_TEMP_DIR 2>/dev/null || echo -n /run/user/$UID
  )
export XDG_CACHE_HOME="${XDG_DATA_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
mkdir -p "$XDG_RUNTIME_DIR" "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"

# Coerce non-conformant apps to use XDG-like file structures where feasible.
# abbr
export ABBR_TMPDIR="$XDG_RUNTIME_DIR/zsh-abbr"
# Android Studio
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"
export ANDROID_AVD_HOME="$ANDROID_USER_HOME/avd"
command -v adb >/dev/null 2>&1 && alias adb="HOME=\"$ANDROID_USER_HOME\" adb"
# Copilot
export COPILOT_HOME="$XDG_DATA_HOME/copilot"
# gnupg
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
# go
export GOPATH="$XDG_DATA_HOME/go"
# Hammerspoon
[ -n "$IS_MACOS" ] &&
  defaults write org.hammerspoon.Hammerspoon MJConfigFile "${XDG_CONFIG_HOME}/hammerspoon/init.lua"
# less, for versions lower than 598
export LESSHISTFILE="$XDG_STATE_HOME/lesshst"
# z4h / ncurses
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
rm -rf ~/.terminfo # z4h will default to this if it exists
# Node.js
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
# Python, for versions lower than 3.13.0a3
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
# screen
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
# shell history
export HISTFILE="$XDG_STATE_HOME/$(shell_name)_history"
[ -e "$HISTFILE" ] || touch "$HISTFILE"
# SQLite
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
# tmux, for versions lower than 3.1
# While this SHOULD be an alias ($TMUX_CONFIG isn't a var used by tmux itself),
# using a variable here and aliasing later makes bootstrapping easier.
export TMUX_CONFIG="$XDG_CONFIG_HOME/tmux/tmux.conf"
# Vim
export GVIMINIT='let $MYGVIMRC="$XDG_CONFIG_HOME/vim/gvimrc" | source $MYGVIMRC'
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
# wget
command -v wget >/dev/null 2>&1 && alias wget="wget --hsts-file=\"$XDG_DATA_HOME/wget-hsts\""
