#!/usr/bin/env zsh
#MISE dir="{{cwd}}"
#MISE alias="node.js"
#MISE depends=["init:config"]
#MISE depends_post=["init:node:package-json", "init:node:path"]
#USAGE arg "[version]"

# Enforce node version during development.
mise set NPM_CONFIG_ENGINE_STRICT=true

# Install Node.js.
mise use node@$usage_version

# Lock Node.js version in package.json, if not already locked.
if [[ -n ${usage_version} || $(jq -r '.engines.node' package.json) == null ]]; then
  installed=$(mise ls --local --current --json node | jq -r '.[0].version')
  if [[ -n ${installed} && ${installed} != null ]]; then
    echo '{}' | jq --arg v "^$installed" '.engines.node = $v' > package.node.json
  fi
fi
# Prefer package.json.
rm -f .node-version .nvmrc
