#!/usr/bin/env zsh
#MISE dir="{{cwd}}"

if [[ -z package*.json(#qN) ]] {
  echo "No package.json file(s) found."
  return 1
}

# Normalize properties.
jq --indent 2 '.' << EOF > package.Ω.json
{
  "main": null,
  "module": null
}
EOF

# Merge temporary package.*.json files (e.g. package.corepack.json) into package.json.
tee package.json <<< $(
  jq -s --indent 2 '
    # Recursively combine slurped inputs into single object.
    reduce .[] as $obj ({}; . * $obj)
    # Delete null values.
    | del(..|nulls)
  ' package*.json(oe:'REPLY=(${REPLY%.*})':) # Sort by name without file extension.
) > /dev/null
rm -f package.*.json(N)
