#!/usr/bin/env zsh
#MISE dir="{{cwd}}"
#MISE depends=["init:config", "init:node"]
#MISE depends_post=["init:node:package-json"]
#USAGE arg "[node-version]"

mise run init:node $usage_node_version

mise run init:node:corepack pnpm -x pnpx
[[ -f package.json ]] || mise exec -c 'pnpm init --init-package-manager false --init-type module &> /dev/null'
