#!/usr/bin/env sh

# Source - https://stackoverflow.com/a/23011530
# Posted by mklement0, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-14, License - CC BY-SA 4.0
shell_name() {
  local trueExe nextTarget 2>/dev/null # ignore error in shells without `local`
  # Determine the shell executable filename.
  if [ -r /proc/$$/cmdline ]; then
    trueExe=$(cut -d '' -f1 /proc/$$/cmdline) || return 1
  else
    trueExe=$(ps -p $$ -o comm=) || return 1
  fi
  # Strip a leading "-", as added e.g. by macOS for login shells.
  [ "${trueExe#-}" = "$trueExe" ] || trueExe=${trueExe#-}
  # Determine full executable path.
  [ "${trueExe#/}" != "$trueExe" ] || trueExe=$(
    [ -n "$ZSH_VERSION" ] && which -p "$trueExe" || which "$trueExe"
  )
  # If the executable is a symlink, resolve it to its *ultimate*
  # target.
  while nextTarget=$(readlink "$trueExe"); do trueExe=$nextTarget; done
  # on MacOS, sh is not a symlink, but an executable that
  # re-execs /private/var/select/sh, so resolve it
  if [ "$(basename $trueExe)" = "sh" -a -L "/private/var/select/sh" ]; then
    trueExe="/private/var/select/sh";
    while nextTarget=$(readlink "$trueExe"); do trueExe=$nextTarget; done
  fi
  # Output the executable name only.
  printf '%s\n' "$(basename "$trueExe")"
}

# Determine OS type.
case "$(uname)" in
  Darwin)  export IS_MACOS=1;;
  Linux)   export IS_LINUX=1;;
  FreeBSD) export IS_FREEBSD=1;;
  *)       echo "⚠️ Unsupported OS: $(uname)";;
esac
