#!/usr/bin/env sh

# Determine OS type.
case "$(uname)" in
  Darwin) export IS_MACOS=1 ;;
  Linux) export IS_LINUX=1 ;;
  FreeBSD) export IS_FREEBSD=1 ;;
  *) >&2 printf "\e[33m-init\e[39m: unsupported OS '\e[31m$(uname)e[39m'\n" ;;
esac

# Set TMPDIR if not already.
if [ -z "$TMPDIR" ] || [ ! -d "$TMPDIR" ] || [ ! -w "$TMPDIR" ]; then
  if [ -n "$IS_MACOS" ]; then
    export TMPDIR=$(getconf DARWIN_USER_TEMP_DIR)
  elif [ -d "/tmp" ] && [ -w "/tmp" ]; then
    export TMPDIR="/tmp"
  else
    >&2 printf '\e[33m-init\e[39m: could not set \e[31m$TMPDIR\e[39m\n'
  fi
fi

# Explicitly set the XDG basedir spec, sinc some tools ignore it if not set.
[ -z "$XDG_RUNTIME_DIR" ] &&
  export XDG_RUNTIME_DIR=$(
    getconf DARWIN_USER_TEMP_DIR 2>/dev/null || echo -n /run/user/$UID
  )
export XDG_CACHE_HOME="${XDG_DATA_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
mkdir -p "$XDG_RUNTIME_DIR" "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"
