#!/usr/bin/env sh

# Global configurations
export DO_NOT_TRACK=1
export PAGER='less'
# Set editor in order of preference based on what's available.
if command -v nano >/dev/null 2>&1; then
  export VISUAL='nano'
elif command -v pico >/dev/null 2>&1; then
  export VISUAL='pico'
elif command -v vim >/dev/null 2>&1; then
  export VISUAL='vim'
elif command -v vi >/dev/null 2>&1; then
  export VISUAL='vi'
fi
# Compatibility for tools that don't support $VISUAL.
if [ -n "$VISUAL" ]; then
  export EDITOR="$VISUAL"
  export SUDO_EDITOR="$VISUAL"
fi

# App-specific configurations
# GPG
export GPG_TTY="$TTY"
# less
export LESS='-iMR~ --tabs=4 --window=-4'
# man
export MANPAGER='less +Gg' # Show scroll progress in man pages.
# mise
export MISE_FPATH=$XDG_DATA_HOME/mise/zsh/fn
export MISE_MANPATH=$XDG_DATA_HOME/mise/man
# rsync
export RSYNC_PARTIAL_DIR='.rsync-transfer'
# tar
[ -n "$IS_MACOS" ] && export COPYFILE_DISABLE=1 # https://superuser.com/a/260264/308015
