#!/usr/bin/env sh

# Global configurations
export DO_NOT_TRACK=1
export PAGER='less'
export VISUAL='micro'
# Compatibility for tools that don't support $VISUAL.
export EDITOR="$VISUAL"
export SUDO_EDITOR="$VISUAL"

# App-specific configurations
# GPG
export GPG_TTY="$TTY"
# less
export LESS='-iMR~ --tabs=4 --window=-4'
# man
export MANPAGER='less +Gg' # Show scroll progress in man pages.
# mise
export MISE_FPATH="$XDG_DATA_HOME/mise/zsh/fn"
export MISE_GLOBAL_CONFIG_FILE="$XDG_CONFIG_HOME/mise/config.toml"
export MISE_MANPATH="$XDG_DATA_HOME/mise/man"
# rsync
export RSYNC_PARTIAL_DIR='.rsync-transfer'
# tar
[ -n "$IS_MACOS" ] && export COPYFILE_DISABLE=1 # https://superuser.com/a/260264/308015
