#!/usr/bin/env sh

# Coerce non-conformant apps to use XDG-like file structures where feasible.
# abbr
export ABBR_TMPDIR="$XDG_RUNTIME_DIR/zsh-abbr"
# Copilot
export COPILOT_HOME="$XDG_DATA_HOME/copilot"
# gnupg
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
# go
export GOPATH="$XDG_DATA_HOME/go"
# Hammerspoon
[ -n "$IS_MACOS" ] &&
  defaults write org.hammerspoon.Hammerspoon MJConfigFile "${XDG_CONFIG_HOME}/hammerspoon/init.lua"
# less, for versions lower than 598
export LESSHISTFILE="$XDG_STATE_HOME/lesshst"
# z4h / ncurses
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
rm -rf ~/.terminfo # z4h will default to this if it exists
# Node.js
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
# Python, for versions lower than 3.13.0a3
export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
# screen
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
# shell history
export HISTFILE="$XDG_STATE_HOME/${SHELL_NAME}_history"
[ -e "$HISTFILE" ] || touch "$HISTFILE"
# SQLite
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
# tmux, for versions lower than 3.1
alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
# Vim
export GVIMINIT='let $MYGVIMRC="$XDG_CONFIG_HOME/vim/gvimrc" | source $MYGVIMRC'
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
# wget
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
