# https://mise.jdx.dev/configuration/settings.html

[settings]
# Pushes tools' bin-paths to the front of PATH instead of allowing modifications
# of PATH after activation to take precedence.
activate_aggressive = true
# Cache the computed environment (env vars and PATH) to disk. This dramatically
# speeds up nested mise invocations.
env_cache = true
# Path to a file containing environment variables to automatically load.
env_file = '.env'
# Shell-style variable expansion in mise.toml [env] values.
env_shell_expand = true # will become the default in a future release
# Read version files used by other version managers, such as .nvmrc.
idiomatic_version_file_enable_tools = [
  "bun",
  "deno",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "rust",
  "terraform",
  "yarn",
]
# Disable the "command not found" handler to autoinstall missing tool versions.
not_found_auto_install = false
# Config paths that mise will automatically mark as trusted.
trusted_config_paths = [
  '~/dev',
]

[settings.dotnet]
# Sets the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1, disabling .NET
# CLI telemetry.
cli_telemetry_optout = true

[settings.go]
# Override GOBIN if previously set.
set_gobin = true

[settings.npm]
# Package manager to use for installing npm packages.
package_manager = "aube" # https://github.com/jdx/aube

[settings.python]
# Controls how mise handles uv project venvs when a uv.lock file is present.
uv_venv_auto = "create|source" # create the venv if missing and source it

[settings.rust]
# Path to the cargo home directory.
cargo_home = "$XDG_DATA_HOME/cargo"
# Path to the rustup home directory.
rustup_home = "$XDG_DATA_HOME/rustup"

[settings.status]
# Show configured env vars when entering a directory with a mise.toml file.
show_env = true
# Show configured tools when entering a directory with a mise.toml file.
show_tools = true

[tool_alias]
eza-comp = "github:eza-community/eza"
eza-docs = "github:eza-community/eza"
jq-docs = "github:jqlang/jq"
micro = "github:micro-editor/micro"
yq = "github:mikefarah/yq"

[tools.usage]
version = "latest"
# TODO: comp
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/*.1 "$MISE_MANPATH"/man1/
"""

[tools.aube]
version = "latest"
# TODO: docs
postinstall = """
MISE_AUTO_INSTALL=0 mise exec -- aube completion zsh >"$MISE_FPATH"/_aube
"""

[tools.bat]
version = "latest"
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/autocomplete/bat.zsh "$MISE_FPATH"/_bat
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/*.1 "$MISE_MANPATH"/man1/
"""

[tools.eza]
version = "latest"
[tools.eza-comp]
version = "latest"
asset_pattern = "completions-*"
strip_components = "1"
bin_path = "completions-{{ version }}"
filter_bins = ""
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/_eza "$MISE_FPATH"/
"""
[tools.eza-docs]
version = "latest"
asset_pattern = "man-*"
strip_components = "1"
bin_path = "man-{{ version }}"
filter_bins = ""
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/* "$MISE_MANPATH"/man1/
"""

[tools.fd]
version = "latest"
postinstall = """
MISE_AUTO_INSTALL=0 mise exec -- fd --gen-completions zsh >"$MISE_FPATH"/_fd
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/*.1 "$MISE_MANPATH"/man1/
"""

[tools.fx]
version = "latest"
# TODO: docs
postinstall = """
MISE_AUTO_INSTALL=0 mise exec -- fx --comp zsh >"$MISE_FPATH"/_fx
"""

[tools.hwatch]
version = "latest"
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/completion/zsh/_hwatch "$MISE_FPATH"/
ln -fs "$MISE_TOOL_INSTALL_PATH"/man/*.1 "$MISE_MANPATH"/man1/
"""

[tools.micro]
version = "latest"
postinstall = """
mkdir -p "$XDG_STATE_HOME"/micro/backups
ln -fs "$MISE_TOOL_INSTALL_PATH"/*.1 "$MISE_MANPATH"/man1/
"""

[tools.jq]
version = "latest"
# no comp, https://github.com/jqlang/jq/issues/1417
[tools.jq-docs]
version = "latest"
asset_pattern = "jq-*.tar.gz"
filter_bins = ""
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/*.1 "$MISE_MANPATH"/man1/
"""

[tools.ripgrep]
version = "latest"
postinstall = """
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/complete/_rg "$MISE_FPATH"/
ln -fs "$MISE_TOOL_INSTALL_PATH"/*/doc/*.1 "$MISE_MANPATH"/man1/
"""

[tools.yq]
version = "latest"
rename_exe = "yq"
filter_bins = "yq"
postinstall = """
MISE_AUTO_INSTALL=0 mise exec -- yq completion zsh >"$MISE_FPATH"/_yq
ln -fs "$MISE_TOOL_INSTALL_PATH"/*.1 "$MISE_MANPATH"/man1/
"""
