[settings]
# read version files used by other version managers, such as .nvmrc
idiomatic_version_file_enable_tools = [
  "bun",
  "deno",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "rust",
  "terraform",
  "yarn",
]
trusted_config_paths = [
  '~/dev',
]
# load env vars from a dotenv file, see `MISE_ENV_FILE`
env_file = '.env'

[settings.npm]
package_manager = "bun"

[settings.status]
show_env = true
show_tools = true

[tool_alias]
eza-comp = "github:eza-community/eza"
eza-docs = "github:eza-community/eza"
micro = "github:micro-editor/micro"

[tools]
usage = { version = "latest", postinstall = "ln -fs $MISE_TOOL_INSTALL_PATH/*/*.1 $MISE_MANPATH/man1/" }
bat = { version = "latest", postinstall = "ln -fs $MISE_TOOL_INSTALL_PATH/*/autocomplete/bat.zsh $MISE_FPATH/_bat; ln -fs $MISE_TOOL_INSTALL_PATH/*/*.1 $MISE_MANPATH/man1/" }
fd = { version = "latest", postinstall = "fd --gen-completions zsh >$MISE_FPATH/_fd; ln -fs $MISE_TOOL_INSTALL_PATH/*/*.1 $MISE_MANPATH/man1/" }
eza = "latest"
eza-comp = { version = "latest", asset_pattern = "completions-*", strip_components = "1", bin_path = "completions-{{ version }}", filter_bins = "", postinstall = "ln -fs $MISE_TOOL_INSTALL_PATH/*/_eza $MISE_FPATH/" }
eza-docs = { version = "latest", asset_pattern = "man-*", strip_components = "1", bin_path = "man-{{ version }}", filter_bins = "", postinstall = "ln -fs $MISE_TOOL_INSTALL_PATH/*/* $MISE_MANPATH/man1/" }
fx = { version = "latest", postinstall = "fx --comp zsh > $MISE_FPATH/_fx" }
hwatch = { version = "latest", postinstall = "ln -fs $MISE_TOOL_INSTALL_PATH/completion/zsh/_hwatch $MISE_FPATH/; ln -fs $MISE_TOOL_INSTALL_PATH/man/*.1 $MISE_MANPATH/man1/" }
jq = "latest"
yq = "latest"
