[settings]
# read version files used by other version managers, such as .nvmrc
idiomatic_version_file_enable_tools = [
  "bun",
  "deno",
  "go",
  "java",
  "node",
  "npm",
  "pnpm",
  "python",
  "ruby",
  "rust",
  "terraform",
  "yarn",
]
trusted_config_paths = [
  '~/dev',
]

[settings.npm]
package_manager = "bun"

[settings.status]
show_env = true
show_tools = true

[tools]
"cargo:cargo-generate" = "latest"
go = "latest"
"pipx:xkcdpass" = "latest"
